### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by wwj718** [cherezov/orvibo#16]
it does not work on Allone Pro 

![image](https://user-images.githubusercontent.com/3153878/48764568-f3b49280-ecea-11e8-840b-3e1c5beca51f.png)

![image](https://user-images.githubusercontent.com/3153878/48764670-3d04e200-eceb-11e8-8a46-863840ad1025.png)

The firmware version is up to date : v1.0.4

![image](https://user-images.githubusercontent.com/3153878/48764678-4726e080-eceb-11e8-8c9a-e6a63d0695cf.png)

**Comment by scrhall** [comment]
Same problem with firm version 1.0.2

**Comment by novalu** [comment]
I'm afraid that AllOne and AllOne Pro is different product, isn't? I've found this [product](https://www.aliexpress.com/item/Orvibo-Allone-Pro-Universal-Smart-WIFI-IR-RF-Remote-Controller-433MHz-Works-With-Alexa-Google-Home/32873232158.html) and there is listed that AllOne Pro cannot learn new IR commands, but according to README.md it should. Does anyone know more?
