### ISSUE TITLE
No response on Windows, works fine on macbook

### ISSUE THREAD

**Issue by zdunaisky-chwy** [cherezov/orvibo#2]
Hello,

First, thank you for writing this awesome script. It was working great for me but suddenly stopped and I can't figure out why. I assume it's something environmental but I'm an Android dev - not a python guy so I'm a bit lost. I was hoping you could maybe point me in a direction.

I had the script working fine on windows 10 with Python 3.5. It actually still works when I run it on my macbook. I also installed Python 2.7 and still no luck.

If I run `python orvibo.py` it returns nothing. If I run the same thing from my macbook I get `Orvibo[type=irda, ip=192.168.1.87, mac=accfblahblahblah]`

I've tried variations of the command with all the parameters set and not set. I can even successfully ping the IP address from the windows machine.

Any ideas? I'm out of em and about to figure out how to debug python.

Thanks!
Zach

**Comment by zdunaisky-chwy** [comment]
Turns out VirtualBox was messing up the device discovery. I've temporarily uninstalled virtualbox and it's working again!

**Comment by cherezov** [comment]
Thanks for your feedback!
I've actually figured out that installing VirtualBox on at least windows machine may lead to changing default network interface to virtual one. You may check it with the command `ipconfig -all`
As a quick workaround you may disable virtual box network connection somewhere in the Control Panel (e.g Network and Internet / Network Connections for Win7)

Hope this helps

**Comment by zdunaisky-chwy** [comment]
I ended up just uninstalling virtualbox and using vmware. I'm not familiar enough with how the network interfaces work to fix discovery. I tried a bunch of things but nothing worked.

Thanks again!
