### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by moskovskiy82** [cherezov/orvibo#4]
Don't know if it is a bug but...

$ python orvibo.py
Orvibo[type=irda, ip=1xx.1xx.x.83, mac=xxxxx3565xxx]
Orvibo[type=None, ip=1xx.xx.x.3, mac=xxxxxx2e6xxx]
$ python3 orvibo.py
Orvibo[type=irda, ip=1xx.1xx.x.83, **mac=Unknown**]
Orvibo[type=None,  ip=1xx.xx.x.3, **mac=Unknown**]

**Comment by cherezov** [comment]
> Orvibo[type=None, ip=1xx.xx.x.3, mac=Unknown] 

And actually what is the type of the device?

**Comment by cherezov** [comment]
Bug fixed. Thanks for reporting!
