### ISSUE TITLE
RF 433 learning

### ISSUE THREAD

**Issue by clyra** [cherezov/orvibo#5]
Hi,

First, thanks for you work. now... is it possible to learn RF codes from other brands or just orvibo products? I have a pair of Livolo switchs and a 4 button rf remote control, but the orvibo seems to ignore it.

**Comment by cherezov** [comment]
Hi!
Orvibo learns any RF codes with 433MHz frequency. Brand doesn't  matter.
Please check your device is 433MHz and let me see how do you use the script.

**Comment by clyra** [comment]
Hi,

Thanks for the really quick reply. I'm using a OSX with a "brewed"
installed python3. What i did:

lyra$ python3 orvibo.py
Orvibo[type=socket, ip=192.168.0.210, mac=accf2365a1c2]
Orvibo[type=irda, ip=192.168.0.207, mac=accf2351eaae]
lyra$ python3 orvibo.py -i 192.168.0.207 -t light1.rf
Orvibo[type=irda, ip=192.168.0.207, mac=accf2351eaae]
WARNING:Orvibo@192.168.0.207:Nothing happend during 15 sec

sometimes I get this:
lyra$ python3 orvibo.py -i 192.168.0.207 -t light1.rf
Orvibo[type=irda, ip=192.168.0.207, mac=accf2351eaae]
Traceback (most recent call last):
  File "orvibo.py", line 572, in <module>
    signal = d.learn(teach)
  File "orvibo.py", line 431, in learn
    signal = signal_split[1][6:]
IndexError: list index out of range

On Sun, Jun 26, 2016 at 1:42 PM, Pavel notifications@github.com wrote:

> Hi!
> Orvibo learns any RF codes with 433MHz frequency. Brand doesn't matter.
> Please check your device is 433MHz and let me see how do you use the
> script.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/cherezov/orvibo/issues/5#issuecomment-228610103, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEjpGn6hmnJ98RTf66PncSIS_vHFShkWks5qPqvdgaJpZM4I-lm6
> .

## 

Christian Lyra
PoP-PR/RNP

**Comment by cherezov** [comment]
> Orvibo[type=irda, ip=192.168.0.207, mac=accf2351eaae] 
> WARNING:Orvibo@192.168.0.207:Nothing happend during 15 sec

You emitted the RF signal on your device while red ring was blinking slowly on your AllOne, but AllOne didn't catch the signal while 15 seconds, right?

BTW, I've just googled livolo switches and figured out that they all works on 433.92MHz, which is a bit different than 433MHz Orvibo AllOne works on. Seems it is the root cause of your problem. Sorry.

**Comment by clyra** [comment]
i see... anyway, thank you for your support. The allinone will be only useful as a IR bridge to me which is still fine :-).

**Comment by cherezov** [comment]
You are welcome!
Thanks for using the module and for your report :)
