### ISSUE TITLE
Orvibo AlloneR1 does not learn or emit RF433!

### ISSUE THREAD

**Issue by huongminh** [cherezov/orvibo#7]
Hi,

Thank you for your great job! I use your script and an AlloneR1 together with Domoticz and Homebridge to control all my IR devices now in my house by Siri voice commands. However, I can't control my Blinds which run on RF433Mhz. It seems the AlloneR1 does not understand RF433 at all when I put it in learn mode and try to teach it with my Blind RF433 remote. The Orvibo red light (indicating learn mode) would never turn blue and I got timeout after 15 seconds. It would work well with a IR remote. I am sure my blinds runs on RF433Mhz. I also tried the RF433 learning successfully with a Broadlink RM Pro (similar device as Orvibo AlloneR1 but control must be via the RM bridge which runs only on Android). Please help!

**Comment by andreiiliuta** [comment]
Hi Pavel,

I am having the same problem. Cannot learn RF433. Is there any way we can help troubleshooting?

**Comment by cherezov** [comment]
Guys, thank you for your feedbacks!
I'll double check this behavior this week.

**Comment by cherezov** [comment]
Well, I've tried to grab signal from my simple RF433 helicopter remote and it was successfully grabbed.
Could you guys use orvibo.py with extended output like:

``` shell
orvibo.py -L info -i 192.168.1.37 -t test.rf
```

please, and paste the output here?

I also suppose that not all cheap devices has exact 433MHz frequency (even AllOne) and this can be the root cause why some devices work with Orvibo, and some not.

**Comment by huongminh** [comment]
This is what I got:

pi@raspberrypi:~/domoticz/scripts $ /home/pi/domoticz/scripts/orvibo.py -L info -i 192.168.1.117 -m accf2378d33e -x irda -t /home/pi/domoticz/scripts/AlloneR1/Testing.rf
Orvibo[type=irda, ip=192.168.1.117, mac=accf2378d33e]
INFO:Orvibo@192.168.1.117:Waiting 15 sec for IR/RF433 signal...
INFO:Orvibo@192.168.1.117:The rest time: 14 sec
INFO:Orvibo@192.168.1.117:The rest time: 13 sec
INFO:Orvibo@192.168.1.117:The rest time: 12 sec
INFO:Orvibo@192.168.1.117:The rest time: 11 sec
INFO:Orvibo@192.168.1.117:The rest time: 10 sec
INFO:Orvibo@192.168.1.117:The rest time: 9 sec
INFO:Orvibo@192.168.1.117:The rest time: 8 sec
INFO:Orvibo@192.168.1.117:The rest time: 7 sec
INFO:Orvibo@192.168.1.117:The rest time: 6 sec
INFO:Orvibo@192.168.1.117:The rest time: 5 sec
INFO:Orvibo@192.168.1.117:The rest time: 4 sec
INFO:Orvibo@192.168.1.117:The rest time: 3 sec
INFO:Orvibo@192.168.1.117:The rest time: 2 sec
INFO:Orvibo@192.168.1.117:The rest time: 1 sec
INFO:Orvibo@192.168.1.117:The rest time: 0 sec
WARNING:Orvibo@192.168.1.117:Nothing happend during 15 sec

**Comment by huongminh** [comment]
Are you sure your toy helicopter runs on 433Mhz RF. I have one toy helicopter but it runs on IR. I have 2 AlloneR1 sets and 3 RF433 blinds so I tested all of them. I also tried a broadlink RMpro which is similar to AlloneR1 and there it worked with my RF433.

**Comment by cherezov** [comment]
@huongminh 
Well, I'm afraid your device 433MHz doesn't the same as AllOne 433MHz and I can't help you with this unfortunately.

**Comment by cherezov** [comment]
@huongminh thanks for provided output and description, it'll help me to dig the code.
AFAIR my helicopter has a 433MHz sticker, but who knows. I din't try to disassembly it to check :)

**Comment by huongminh** [comment]
Thank you for your effort! I really appreciate it! Both my AlloneR1s work reliably with your script , which I put in Domoticz to control all my IR devices. Waiting for your update on the RF feature.

**Comment by huongminh** [comment]
Thank you for your effort! I really appreciate it! Both my AlloneR1s work reliably with your script , which I put in Domoticz to control all my IR devices. Waiting for your update on the RF feature.

**Comment by cherezov** [comment]
Bad news everyone.
["Only allone can match with Orvibo RF switch, and can't support any other RF devices."](http://community.orvibo.com/t/how-to-learn-rf-remote-controls/151)

**Comment by huongminh** [comment]
Thank you for your update. So I understand that there is no way to make the Allone to learn and emit RF433.

**Comment by cherezov** [comment]
Sorry for misleading description of my module, I've already removed RF433 references from it. 
Actually I found a way to learn AllOne emit RF433 to control Orvibo SmartSwitch and going to add it soon, but this doesn't work for my RF433 remote for light. May be your remote will occasionally work with this approach.

**Comment by SeNike** [comment]
> Actually I found a way to learn AllOne emit RF433 to control Orvibo SmartSwitch 

 Please explain how to do this?. Whose signal must learn AllOne? I have no RF-emitter, such as Orvibo remote control.

**Comment by cherezov** [comment]
@SeNike 
Actually AllOne doesn't learn RF signal of Orvibo SmartSwitch :)
After long press on SmartSwitch it starts listening for RF signal. AllOne (software actually, e.g orvibo.py) generates random 7 bytes key and sends RF signal via AllOne. AllOne modiffies(!) a bit and emits. SmartSwitch received RF signal and saved it automatically.
Thus emitting previously generated 7 bytes with additional on/off byte will turn on/off SmartSwitch button accordingly.

Hope that help :)

**Comment by SeNike** [comment]
Thanks! This works fine!
learn:
orvibo.py -i 192.168.1.75 -m accf232b3d9c -x irda -t smartswitch.rf -r
emit:
orvibo.py -i 192.168.1.75 -m accf232b3d9c -x irda -e smartswitch.rf -r -s on

**Comment by supakdee** [comment]
Correction:
I search in other issue - it seems to be an issue with python command. Need to use instead python3

With below code, it works perfectly fine.

pi@raspberrypi:~/orvibo/orvibo $ python3 orvibo.py -i 192.168.0.14 -m accf236576b2 -x irda -e smartswitch.rf -r -s off
Orvibo[type=irda, ip=192.168.0.14, mac=accf236576b2]
Emit RF done.
pi@raspberrypi:~/orvibo/orvibo $ python3 orvibo.py -i 192.168.0.14 -m accf236576b2 -x irda -e smartswitch.rf -r -s on
Orvibo[type=irda, ip=192.168.0.14, mac=accf236576b2]
Emit RF done.

---

Original:

Hi,

IR teach & emit work very well.

However, when I tried to teach RF, I got below error. Can you help to let me know what I should do to resolve it?

And since Orvibo itself generate RF command, how will it grab a RF command? Should i call a teach command in python then use Wiwo app to turn on RF switch?

pi@raspberrypi:~/orvibo/orvibo $ python orvibo.py -i 192.168.0.14 -m accf236576b2 -x irda -t smartswitch.rf -r
Orvibo[type=irda, ip=192.168.0.14, mac=accf236576b2]
Traceback (most recent call last):
  File "orvibo.py", line 744, in <module>
    d.emit_ir(b' ')
  File "orvibo.py", line 574, in emit_ir
    with open(signal, 'rb') as f:
IOError: [Errno 2] No such file or directory: ' '

**Comment by cherezov** [comment]
Do I understand you right that you've tried to teach orvibo to emit RF for your SmartSwitch and it didn't work with py2.7, but works with py3?

**Comment by supakdee** [comment]
Hi Cherezov,
Correct.
With py2.7, the command for RF give error.
It works perfectly fine with py3

**Comment by huongminh** [comment]
Hi Cherezov,
I found Orvibo just released a new version of Allone Pro that fullly support RF433, not just the Orvibo smart switch. Any chance it will work with your code?

**Comment by cherezov** [comment]
Hi @huongminh ! Thanks for letting me know, but I'm actually not sure that current code will work with new Orvibo device. I believe it requires additional reverse engineering. 
May be if I'll get my own device or someone who own it will assist me with network packets dump I'll support it in the script.
Thanks again :octocat:

**Comment by huongminh** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Thank you. And looking forward to the good news... 


Sent from Yahoo Mail for iPhone


On Monday, April 10, 2017, 3:11 PM, Pavel <notifications@github.com> wrote:


Hi @huongminh ! Thanks for letting me know, but I'm actually not sure that current code will work with new Orvibo device. I believe it requires additional reverse engineering.
May be if I'll get my own device or someone who own it will assist me with network packets dump I'll support it in the script.
Thanks again

**Comment by mdzidic** [comment]
Just to make it clear there are two version of Orvibo Allone:
- Orvibo Allone WiWo-R1 (IR only)
- Orvibo Allone Pro (IR and RF)

**Comment by polmonta** [comment]
Hey @cherezov! I know it's a bit late, but I am willing to help with the RF433 problem. I own several blinds and the Orvibo Allone Pro (IR and RF). The blinds work fine when using the orvibo app. Are you still willing to implement this to you code? I am trying to link my blinds with HomeKit (trough Homebridge) and I would greately appericate it. If you are interested in the implementation of the new features to your code, I would be delighted to help.
